kind: pipeline
name: default

## UMI development steps
steps:
- name: baseimage
  image: plugins/docker
  settings:
    repo: unitedmotionideas/frontbase
    target: baseimage
    dockerfile: ./Dockerfile.image
    build_args:
      - APP_NAME=umi
      - ENV_NAME=dev
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - push
    branch:
      - development

- name: dockerDev
  image: plugins/docker
  settings:
    target: buildinstance
    auto_tag: true
    build_args:
      - APP_NAME=umi
      - ENV_NAME=dev
    repo: unitedmotionideas/umi-application-front
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - push
    branch:
      - development

- name: rancherDev
  image: peloton/drone-rancher
  settings:
    url: http://206.189.56.176:8080
    access_key:
      from_secret: rancher_access
    secret_key:
      from_secret: rancher_secret
    service: dev/umiapplicationfront
    docker_image: unitedmotionideas/umi-application-front:latest
    timeout: 240
  when:
    event:
    - push
    branch:
    - development

## UMI production steps
## This will build the base image. The base image for the front is the same for all instances
- name: baseimageProd
  image: plugins/docker
  settings:
    repo: unitedmotionideas/frontbase
    target: baseimage
    dockerfile: ./Dockerfile.image
    build_args:
      - APP_NAME=umi
      - ENV_NAME=dev
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - push
    branch:
      - development
      -
- name: dockerProd
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: umi
    build_args:
      - APP_NAME=umi
      - ENV_NAME=production
      - VERSION=${DRONE_TAG}
    repo: unitedmotionideas/umi-application-front
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag

- name: rancherProd
  image: peloton/drone-rancher
  settings:
    url: http://206.189.56.176:8080
    access_key:
      from_secret: rancher_access
    secret_key:
      from_secret: rancher_secret
    service: "frontstack/umiapplicationfront"
    docker_image: "unitedmotionideas/umi-application-front:${DRONE_TAG}-umi"
    timeout: 240
  when:
    event:
      - tag