kind: pipeline
name: default
type: docker

## UMI development steps -
steps:
- name: baseimage
  image: plugins/docker
  environment:
    NPM_READONLY_TOKEN:
      from_secret: npm_ro_token
  settings:
    repo: unitedmotionideas/frontbase
    build_args_from_env:
      - NPM_READONLY_TOKEN
    target: baseimage
    dockerfile: ./Dockerfile.image
    build_args:
      - APP_NAME=umi
      - ENV_NAME=dev
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - push
    branch:
      - development

- name: dockerDev
  image: plugins/docker
  depends_on: [baseimage]
  settings:
    target: buildinstance
    build_args:
      - APP_NAME=umi
      - ENV_NAME=dev
    repo: unitedmotionideas/umi-application-front
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - push
    branch:
      - development

- name: rancherDev
  image: peloton/drone-rancher
  depends_on: [dockerDev]
  settings:
    url: http://206.189.56.176:8080
    access_key:
      from_secret: rancher_access
    secret_key:
      from_secret: rancher_secret
    service: dev/umiapplicationfront
    docker_image: unitedmotionideas/umi-application-front:latest
    timeout: 240
  when:
    event:
      - push
    branch:
      - development

## UMI production steps
## This will build the base image. The base image for the front is the same for all instances
- name: baseimageProd
  image: plugins/docker
  environment:
    NPM_READONLY_TOKEN:
      from_secret: npm_ro_token
  settings:
    auto_tag: true
    repo: unitedmotionideas/frontbase
    build_args_from_env:
      - NPM_READONLY_TOKEN
    target: baseimage
    dockerfile: ./Dockerfile.image
    build_args:
      - APP_NAME=umi
      - ENV_NAME=production
      - VERSION=${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag

- name: dockerProd
  depends_on: [baseimageProd]
  image: plugins/docker
  settings:
    target: buildinstance
    auto_tag: true
    auto_tag_suffix: umi
    build_args:
      - APP_NAME=umi
      - ENV_NAME=production
      - VERSION=${DRONE_TAG}
    repo: unitedmotionideas/umi-application-front
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag

- name: rancherProd
  depends_on: [dockerProd]
  image: peloton/drone-rancher
  settings:
    url: http://206.189.56.176:8080
    access_key:
      from_secret: rancher_access
    secret_key:
      from_secret: rancher_secret
    service: "frontstack/umiapplicationfront"
    docker_image: "unitedmotionideas/umi-application-front:${DRONE_TAG}-umi"
    timeout: 240
  when:
    event:
      - tag

## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##
## ## ## ## ## ## ## ## WHITE LABEL ## ## ## ## ## ## ## ## ##
## We need to organize this in groups of three, otherwise,  ##
## the machine won't stand the charge. ## ## ## ## ## ## ## ##
## Group 1: [umi, dynergie, multivalente]
## Group 2: [inomer, novanexia, salveo]
## Group 3: [schneider, bnp]
## Dynergie production steps
- name: dockerProdDynergie
  depends_on: [baseimageProd, dockerProd]
  image: plugins/docker
  settings:
    target: buildinstance
    auto_tag: true
    auto_tag_suffix: dynergie
    build_args:
      - APP_NAME=dynergie
      - ENV_NAME=production
      - VERSION=${DRONE_TAG}
    repo: unitedmotionideas/umi-application-front
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag

- name: rancherProdDynergie
  depends_on: [dockerProdDynergie]
  image: peloton/drone-rancher
  settings:
    url: http://206.189.56.176:8080
    access_key:
      from_secret: rancher_access
    secret_key:
      from_secret: rancher_secret
    service: "frontstack/umiapplicationfront-dynergie"
    docker_image: "unitedmotionideas/umi-application-front:${DRONE_TAG}-dynergie"
    timeout: 240
  when:
    event:
      - tag

  ## Multivalente production steps

- name: dockerProdMultivalente
  depends_on: [baseimageProd, dockerProdDynergie]
  image: plugins/docker
  settings:
    target: buildinstance
    auto_tag: true
    auto_tag_suffix: multivalente
    build_args:
      - APP_NAME=multivalente
      - ENV_NAME=production
      - VERSION=${DRONE_TAG}
    repo: unitedmotionideas/umi-application-front
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag

- name: rancherProdMultivalente
  depends_on: [dockerProdMultivalente]
  image: peloton/drone-rancher
  settings:
    url: http://206.189.56.176:8080
    access_key:
      from_secret: rancher_access
    secret_key:
      from_secret: rancher_secret
    service: "frontstack/umiapplicationfront-multivalente"
    docker_image: "unitedmotionideas/umi-application-front:${DRONE_TAG}-multivalente"
    timeout: 240
  when:
    event:
      - tag

## Group 2
  ## Inomer production steps

#- name: dockerProdInomer
#  depends_on: [baseimageProd, rancherProd, rancherProdDynergie, rancherProdMultivalente]
#  image: plugins/docker
#  settings:
#    target: buildinstance
#    auto_tag: true
#    auto_tag_suffix: inomer
#    build_args:
#      - APP_NAME=inomer
#      - ENV_NAME=production
#      - VERSION=${DRONE_TAG}
#    repo: unitedmotionideas/umi-application-front
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#  when:
#    event:
#      - tag
#
##- name: rancherProdInomer
##  depends_on: [dockerProdInomer]
##  image: peloton/drone-rancher
##  settings:
##    url: http://206.189.56.176:8080
##    access_key:
##      from_secret: rancher_access
##    secret_key:
##      from_secret: rancher_secret
##    service: "frontstack/umiapplicationfront-inomer"
##    docker_image: "unitedmotionideas/umi-application-front:${DRONE_TAG}-inomer"
##    timeout: 240
##  when:
##    event:
##      - tag
#
#  ## Novanexia production steps
#- name: dockerProdNovanexia
#  depends_on: [baseimageProd, rancherProd, rancherProdDynergie, rancherProdMultivalente]
#  image: plugins/docker
#  settings:
#    target: buildinstance
#    auto_tag: true
#    auto_tag_suffix: novanexia
#    build_args:
#      - APP_NAME=novanexia
#      - ENV_NAME=production
#      - VERSION=${DRONE_TAG}
#    repo: unitedmotionideas/umi-application-front
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#  when:
#    event:
#      - tag
#
##- name: rancherProdNovanexia
##  depends_on: [dockerProdNovanexia]
##  image: peloton/drone-rancher
##  settings:
##    url: http://206.189.56.176:8080
##    access_key:
##      from_secret: rancher_access
##    secret_key:
##      from_secret: rancher_secret
##    service: "frontstack/umiapplicationfront-novanexia"
##    docker_image: "unitedmotionideas/umi-application-front:${DRONE_TAG}-novanexia"
##    timeout: 240
##  when:
##    event:
##      - tag
#
#  ## Salveo production steps
#- name: dockerProdSalveo
#  depends_on: [baseimageProd, rancherProd, rancherProdDynergie, rancherProdMultivalente]
#  image: plugins/docker
#  settings:
#    target: buildinstance
#    auto_tag: true
#    auto_tag_suffix: salveo
#    build_args:
#      - APP_NAME=salveo
#      - ENV_NAME=production
#      - VERSION=${DRONE_TAG}
#    repo: unitedmotionideas/umi-application-front
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#  when:
#    event:
#      - tag
#
##- name: rancherProdSalveo
##  depends_on: [dockerProdSalveo]
##  image: peloton/drone-rancher
##  settings:
##    url: http://206.189.56.176:8080
##    access_key:
##      from_secret: rancher_access
##    secret_key:
##      from_secret: rancher_secret
##    service: "frontstack/umiapplicationfront-salveo"
##    docker_image: "unitedmotionideas/umi-application-front:${DRONE_TAG}-salveo"
##    timeout: 240
##  when:
##    event:
##      - tag
#
### Group 3
#  ## Schneider production steps
#- name: dockerProdSchneider
#  depends_on: [baseimageProd]
#  image: plugins/docker
#  settings:
#    target: buildinstance
#    auto_tag: true
#    auto_tag_suffix: schneider
#    build_args:
#      - APP_NAME=schneider
#      - ENV_NAME=production
#      - VERSION=${DRONE_TAG}
#    repo: unitedmotionideas/umi-application-front
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#  when:
#    event:
#      - tag
#
##- name: rancherProdSchneider
##  depends_on: [dockerProdSchneider]
##  image: peloton/drone-rancher
##  settings:
##    url: http://206.189.56.176:8080
##    access_key:
##      from_secret: rancher_access
##    secret_key:
##      from_secret: rancher_secret
##    service: "frontstack/umiapplicationfront-schneider"
##    docker_image: "unitedmotionideas/umi-application-front:${DRONE_TAG}-schneider"
##    timeout: 240
##  when:
##    event:
##      - tag
#
#  ## BNP Paribas production steps
#- name: dockerProdBNP
#  depends_on: [baseimageProd]
#  image: plugins/docker
#  settings:
#    target: buildinstance
#    auto_tag: true
#    auto_tag_suffix: bnpparibas
#    build_args:
#      - APP_NAME=bnpparibas
#      - ENV_NAME=production
#      - VERSION=${DRONE_TAG}
#    repo: unitedmotionideas/umi-application-front
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#  when:
#    event:
#      - tag
#
##- name: rancherProdBNP
##  depends_on: [dockerProdBNP]
##  image: peloton/drone-rancher
##  settings:
##    url: http://206.189.56.176:8080
##    access_key:
##      from_secret: rancher_access
##    secret_key:
##      from_secret: rancher_secret
##    service: "frontstack/umiapplicationfront-bnpparibas"
##    docker_image: "unitedmotionideas/umi-application-front:${DRONE_TAG}-bnpparibas"
##    timeout: 240
##  when:
##    event:
##      - tag
