export const environment = {
  local: true,
  production: false,
  env: 'local',
  apiUrl: 'http://localhost:3000/api',
  etherpadUrl: 'http://localhost:9001',
  clientUrl: 'http://localhost:4200',
  companyName: 'Multivalente',
  companyShortName: 'Multivalente',
  domain: 'multivalente',
  quizUrl: 'http://localhost:4200',
  grafanaUrl: 'http://localhost:3013',
  companyURL: 'www.multivalente.com',
  logoURL: 'https://res.cloudinary.com/umi/image/upload/v1528460832/whitelabel/multivalente/logo-multivalente-3.png',
  logoSynthURL: 'https://res.cloudinary.com/umi/image/upload/v1529571635/whitelabel/multivalente/logo-multivalente-bg.png',
  background: 'https://res.cloudinary.com/umi/image/upload/v1524662280/app/default-images/sign-background.jpg',
  commercialContact: 'contact@multivalente.com',
  secureCookie: false,
  cookieTime: 48 * 3600 * 1000
};
