export const environment = {
  local: false,
  production: true,
  env: 'prod',
  apiUrl: 'https://appv3.umi.us/api',
  etherpadUrl: 'https://etherpad.umi.us',
  clientUrl: 'https://dynergie.umi.us',
  companyName: 'Dynergie',
  companyShortName: 'Dynergie',
  domain: 'dynergie',
  quizUrl: 'https://quiz.umi.us',
  grafanaUrl: 'https://grafana.umi.us',
  companyURL: 'https://www.dynergie.eu',
  logoURL: 'https://res.cloudinary.com/umi/image/upload/app/logo-dynergie.png',
  background: 'https://res.cloudinary.com/umi/image/upload/v1524662280/app/default-images/sign-background.jpg',
  logoSynthURL: 'https://res.cloudinary.com/umi/image/upload/app/logo-dynergie.png',
  commercialContact: 'contact@dynergie.eu',
  secureCookie: true,
  cookieTime: 48 * 3600 * 1000
};
