export const environment = {
  local: false,
  production: true,
  env: 'prod',
  apiUrl: 'https://appv3.umi.us/api',
  etherpadUrl: 'https://etherpad.umi.us',
  clientUrl: 'https://imr.inomer.fr',
  companyName: 'INOMER',
  companyShortName: 'INOMER',
  domain: 'inomer',
  quizUrl: 'https://quiz.umi.us',
  grafanaUrl: 'https://grafana.umi.us',
  companyURL: 'imr.inomer.fr',
  logoURL: 'https://res.cloudinary.com/umi/image/upload/v1524213523/whitelabel/inomer/logo-inomer.png',
  logoSynthURL: 'https://res.cloudinary.com/umi/image/upload/v1529571635/whitelabel/inomer/logo-inomer-wbg.png',
  background: 'https://res.cloudinary.com/umi/image/upload/v1524662280/app/default-images/sign-background.jpg',
  commercialContact: 'contact@inomer.fr',
  secureCookie: true,
  cookieTime: 48 * 3600 * 1000
};
