export const environment = {
  local: true,
  production: false,
  env: 'local',
  apiUrl: 'http://localhost:3000/api',
  etherpadUrl: 'http://localhost:9001',
  clientUrl: 'http://localhost:4200',
  companyName: 'INOMER',
  companyShortName: 'INOMER',
  domain: 'inomer',
  quizUrl: 'http://localhost:4200',
  grafanaUrl: 'http://localhost:3013',
  companyURL: 'https://imr.inomer.fr',
  logoURL: 'https://res.cloudinary.com/umi/image/upload/v1524213523/whitelabel/inomer/logo-inomer.png',
  logoSynthURL: 'https://res.cloudinary.com/umi/image/upload/v1529571635/whitelabel/inomer/logo-inomer-wbg.png',
  background: 'https://res.cloudinary.com/umi/image/upload/v1524662280/app/default-images/sign-background.jpg',
  commercialContact: 'contact@inomer.fr',
  secureCookie: true,
  cookieTime: 48 * 3600 * 1000
};
