export const environment = {
  local: false,
  production: true,
  env: 'prod',
  apiUrl: 'https://appv3.umi.us/api',
  etherpadUrl: 'https://etherpad.umi.us',
  clientUrl: 'https://bnpparibas.umi.us',
  companyName: 'BNP Paribas (demo)',
  companyShortName: 'BNP (demo)',
  domain: 'bnpparibas',
  quizUrl: 'https://quiz.umi.us',
  grafanaUrl: 'https://grafana.umi.us',
  companyURL: 'https://group.bnpparibas',
  logoURL: 'https://res.cloudinary.com/umi/image/upload/v1548164448/whitelabel/bnpparibas/logo-bnp.png',
  logoSynthURL: 'https://res.cloudinary.com/umi/image/upload/v1548164448/whitelabel/bnpparibas/logo-bnp.png',
  background: 'https://res.cloudinary.com/umi/image/upload/v1524662280/app/default-images/sign-background.jpg',
  commercialContact: 'contact@bnpparibas.com',
  secureCookie: true,
  cookieTime: 48 * 3600 * 1000
};
