export const environment = {
  local: false,
  production: true,
  env: 'demo',
  apiUrl: 'https://demo.umi.us/api',
  etherpadUrl: 'https://etherpad-demo.umi.us',
  clientUrl: 'https://umicli-demo.umi.us',
  companyName: 'United Motion Ideas (demo)',
  companyShortName: 'UMI (demo)',
  domain: 'umi',
  quizUrl: 'https://quiz.umi.us',
  grafanaUrl: 'https://grafana.umi.us',
  companyURL: 'https://www.umi.us',
  logoSynthURL: 'https://res.cloudinary.com/umi/image/upload/app/default-images/company-logo/logo-umi-trans-2020.png',
  logoURL: 'https://res.cloudinary.com/umi/image/upload/app/default-images/company-logo/logo-umi-animated-2020.gif',
  background: 'https://res.cloudinary.com/umi/image/upload/f_auto/app/default-images/backgrounds/umi-welcome-picture-2021.jpg',
  commercialContact: 'achampagne@umi.us',
  secureCookie: true,
  cookieTime: 3600 * 1000
};
