export const environment = {
  local: false,
  production: true,
  env: 'prod',
  apiUrl: 'https://appv3.umi.us/api',
  etherpadUrl: 'https://etherpad.umi.us',
  clientUrl: 'http://dvoc.salveo.fr',
  companyName: 'Groupe SALVEO',
  companyShortName: 'SALVEO',
  domain: 'salveo',
  quizUrl: 'https://quiz.umi.us',
  grafanaUrl: 'https://grafana.umi.us',
  companyURL: 'salveo.fr',
  logoURL: 'https://salveo.fr/wp-content/uploads/2017/06/SALVEO-Logo-2016-FR.jpg',
  logoSynthURL: 'https://salveo.fr/wp-content/uploads/2017/06/SALVEO-Logo-2016-FR.jpg',
  background: 'https://res.cloudinary.com/umi/image/upload/v1524662280/app/default-images/sign-background.jpg',
  commercialContact: 'contact@salveo.fr',
  secureCookie: true,
  cookieTime: 48 * 3600 * 1000
};
