#!/bin/bash


#####
#TEMP
#####
#IMAGE_NAME="umi-application-front:jdc"
#CACHE_TAG="vendor1"

#$APP_NAME --environment=$BUILD_ENV $OTHER_PARAMS
#FRONT_VERSION="umi"
#BUILD_ENV="prod"
#OTHER_PARAMS=""

if [[ $CACHE_TAG == *"vendor"* ]]
then
  FRONT_VERSION=$CACHE_TAG
  BUILD_ENV="prod"
  OTHER_PARAMS="--aot"
else
  if [[ $CACHE_TAG == *"latest"* ]]
  then
    FRONT_VERSION="umi"
    BUILD_ENV="dev"
    OTHER_PARAMS="--aot"
  fi
fi

echo docker build --build-arg APP_NAME=$FRONT_VERSION \
      --build-arg BUILD_ENV=$BUILD_ENV \
      --build-arg OTHER_PARAMS=$OTHER_PARAMS -t $IMAGE_NAME .

docker build --build-arg APP_NAME=$FRONT_VERSION --build-arg BUILD_ENV=$BUILD_ENV  -t $IMAGE_NAME .
