export const environment = {
  local: false,
  production: true,
  env: 'prod',
  apiUrl: 'https://appv3.umi.us/api',
  etherpadUrl: 'https://etherpad.umi.us',
  clientUrl: 'https://novanexia.umi.us',
  companyName: 'Novanexia',
  companyShortName: 'Novanexia',
  domain: 'novanexia',
  quizUrl: 'https://quiz.umi.us',
  grafanaUrl: 'https://grafana.umi.us',
  companyURL: 'https://novanexia.fr/',
  logoURL: 'https://res.cloudinary.com/umi/image/upload/v1548164448/whitelabel/novanexia/novanexia-logo-RVB.png',
  logoSynthURL: 'https://res.cloudinary.com/umi/image/upload/v1548164448/whitelabel/novanexia/novanexia-logo-RVB.png',
  background: 'https://res.cloudinary.com/umi/image/upload/v1524662280/app/default-images/sign-background.jpg',
  commercialContact: 'contact@novanexia.fr',
  secureCookie: true,
  cookieTime: 48 * 3600 * 1000
};
