export const languages: { [code: string]: string } = {
  ar: 'Arabic',
  da:'Danish',
  de:'German',
  el:'Greek',
  en: 'English',
  es:'Spanish',
  fi:'Finnish',
  fr:'French',
  it:'Italian',
  ja:'Japanese',
  ko:'Korean',
  nl:'Dutch',
  no:'Norwegian',
  pl:'Polish',
  pt:'Portuguese',
  ru:'Russian',
  sv:'Swedish',
  tr:'Turkish',
  uk:'Ukrainian',
  zh: 'Chinese',
};
