export const languages: { [code: string]: string } = {
  AR: 'Arabic',
  DA:'Danish',
  DE:'German',
  el:'Greek',
  EN: 'English',
  ES:'Spanish',
  FI:'Finnish',
  FR:'French',
  IT:'Italian',
  JA:'Japanese',
  KO:'Korean',
  NL:'Dutch',
  NO:'Norwegian',
  PL:'Polish',
  PT:'Portuguese',
  RU:'Russian',
  SV:'Swedish',
  TR:'Turkish',
  UK:'Ukrainian',
  zh: 'Chinese',
};
