name: umi-application-front
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

  run-test:
    needs: build
    runs-on: ubuntu-latest
    env:
      NPM_READONLY_TOKEN: ${{secrets.NPM_READONLY_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_READONLY_TOKEN}" > .npmrc
      - run: npm i
      - run: npm test
      - run: rm .npmrc


