export const environment = {
  local: true,
  production: false,
  env: 'local',
  apiUrl: 'http://localhost:3000/api',
  etherpadUrl: 'http://localhost:9001',
  clientUrl: 'http://localhost:4200',
  companyName: 'Schneider Electric (local)',
  companyShortName: 'Schneider (local)',
  domain: 'schneider',
  quizUrl: 'http://localhost:4200',
  grafanaUrl: 'http://localhost:3013',
  companyURL: 'https://www.se.com',
  logoURL: 'https://res.cloudinary.com/umi/image/upload/v1548164448/whitelabel/schneider/schneider-logo-white.png',
  logoSynthURL: 'https://res.cloudinary.com/umi/image/upload/v1548164448/whitelabel/schneider/schneider-logo-black.png',
  background: 'https://res.cloudinary.com/umi/image/upload/v1524662280/app/default-images/sign-background.jpg',
  commercialContact: 'contact@se.com',
  secureCookie: false,
  cookieTime: 48 * 3600 * 1000
};
